@echo off
echo Enabling Mullvad split tunneling (keeps RDP on direct Azure path)...
"C:\Program Files\Mullvad VPN\resources\mullvad.exe" split-tunnel set on
echo Excluding svchost.exe (RDP/Azure services stay on direct path)...
"C:\Program Files\Mullvad VPN\resources\mullvad.exe" split-tunnel app add "C:\Windows\System32\svchost.exe"
echo Excluding python.exe (direct connections bypass tunnel)...
"C:\Program Files\Mullvad VPN\resources\mullvad.exe" split-tunnel app add "C:\Program Files\Python312\python.exe"
echo Starting SOCKS5 server (127.0.0.1:1081, exits via Mullvad VPN tunnel)...
start "" "C:\Program Files\Python312\pythonw.exe" "%~dp0vpn_proxy_bridge.py"
timeout /t 2 /nobreak >nul
"C:\Program Files\Python312\python.exe" -c "import socket; s=socket.create_connection(('127.0.0.1',1081),3); print('Bridge is reachable'); s.close()"
